EarthScope/libmseed

libmseed.map

These are all used in `MS_*` macros.

Add missing global variables to linker table.

---

traceutils.c

Check for null pointer arguments to mst_findmatch and mst_findadjacent.

Check for null pointer arguments

---

msrutils.c

- Modify how an MSRecord structure is freed when there is an invalid sampletype, to avoid a memory leak. This memory leak occurs if the original MSRecord has an invalid sampletype, so that ms_samplesize returns 0, then msr_duplicate leaks memory because the duplicated MSRecord is freed using `free` and not `msr_free`.
- Set pointers to NULL immediately after copying the MSRecord structure, to avoid problems with pointers in the original MSRecord structure and the duplicate pointing to the same memory. These problems occur if there are problems allocating memory, for example if the fsdh field cannot be allocated, then freeing the duplicated MSRecord also frees fields in the original MSRecord. Because msr_duplicate uses memcpy to make the initial copy of the MSRecord, the pointers in the …

Don't alias pointers, correctly free on errors, fix memory leak

---

Makefile

When mseed is added as an ExternalProject to CMake, the installation of
libraries fails silently. The comparison ifneq (wildcard $(LIB_SO))
fails for some reason. This commit creates a common LIB_SO set of
variables for Darwin and Linux so that the ifneq comparison during
install time can be removed.

Makefile mods to work with CMake as ExternalProject

---

tracelist.c

This fixed what I think is a bug in `mstl3_pack()`. The record struct here only receives a pointer to the data and thus should not free it. There is no test for this particular function in the library but in the Python wrapper's I'm working on it works with this change.
There are actually more questions/wishes I have regarding this function:
* This function frees memory from the passed in structs. From a design and practical standpoint I think it should not do this as it did not allocate the memory. A consequence is that when calling this function from any language with some automatic memory management one has to jump through a lot of hoops to not double free it and (at least in my solution) it resulted in an unnecessary copy of the data array. I think this function could and should only …

Don't free record data as it does not belong to the record

---

selection.c

With this PR selections without time windows are also valid. I think it should be like this as it is a fairly common case to only select by SID.
A side not: The documentation does not clearly state how multiple given selections are combined. Judging from the code they are combined with `or`, e.g. as soon a single selection matches a record, that record will be read. I agree with this choice but it should be documented.

A selection without time windows can also be valid

---

selection.c

I assume the filtering is indented to work in a positive way, e.g. retain records with the given publication version.

Fix publication version filtering

---

msrutils.c

The argument to msr3_sampratehz is not checked if it is null, leading to a possible null pointer dereference.

Check for null argument to msr3_sampratehz

---

parseutils.c

Print character, not the pointer to the character, and use the
correct format specifier for a uint32_t, and correctly convert
the uint32_t.

Correct error messages to print correct values

---

libmseed.h

Doing `#define foo(x) (y=x);` will break code like:
```
if (...)
foo(0);
else
foo(1);
```
because semicolon in the macro will be the end of the statement in the `if`, and the semicolon outside the macro will be an empty statement, meaning the `else` is no longer attached to the `if`.
Similarly, placing multiple statements into a macro will cause braceless `if` to break as only the first statement will be within the condition. This occurs a few times with `swapflag` in `parseutils.c`.

Fix statements in macros

---

doc/ms_gswap.3
gswap.c
libmseed.h
packdata.c
parseutils.c
unpack.c
unpackdata.c

Firstly, compilers are smart enough that the naive copy-and-bit shift method is converted to a register load/store + `bswap` intrinsic. Specialized versions only serve to confuse the reader and end up with the same or worse compiled code.
Secondly, the cast to `uint32_t*` on a `float` array (in `msr_decode_float32` via `ms_gswap4a`) appears to violate strict aliasing rules, such that an optimizing compiler _ignores the byte swap entirely_.

Simplify byte swapping routines (v2)

---

Makefile
example/lm_read_timewin.c
fileutils.c

Set the `pubversion` to 0 when calling `ms3_readtracelist_timewin()` to solve the problem mentioned in issue #65 .

always set pubversion to 0 when calling ms3_readtracelist_timewin()

---

gswap.c
libmseed.h
mseedformat.h
packdata.c
unpackdata.c

Firstly, compilers are smart enough that the naive copy-and-bit shift method is converted to a register load/store + `bswap` intrinsic. Specialized versions only serve to confuse the reader and end up with the same or worse compiled code.
Secondly, the cast to `uint32_t*` on a `float` array (in `msr_decode_float32` via `ms_gswap4a`) appears to violate strict aliasing rules, such that an optimizing compiler _ignores the byte swap entirely_.

Simplify byte swapping routines (v3)

---

doc/ms_selection.3

Spotted by Lintian: https://lintian.debian.org/sources/libmseed.

doc: fix typo in ms_selection.3

---

traceutils.c

Check that whence argument to mst_addspan and mst_addmsr is valid, which prevents modifications to MSTrace.numsmaples when the number of samples has not actually changed.
In mst_addmsr and msr_addspan, update the MSTrace.dataquality and MSTrace.samplecnt only when the source data buffer, which is either MSRecord.datasample or a pointer to a datasamples buffer, is non-null and has data samples.

Update numsamples and samplecnt consistently

---

fileutils.c

When calling `ms3_tracelist()` (and thereafter
`ms3_tracelist_selection()`), previously the position within the
file from which records were first read was undefined, because
`fpos` was used uninitialized.  This in general did not cause
problems, but repeated calls to the library could leave `fpos`
taking an arbitrary value, including a negative one.  In that
case, when the negative, non-0 value of `fpos` was read in
`ms3_readmsr_selection()` the first time, it was taken to be a
'legacy' request to start reading records at some non-0 offset
within the file.
Fix this by initializing `fpos` in `ms3_tracelist_selection()`
to 0.
This potential error and its fix was spotted by @bakerb845.
Closes #70.

Fix uninitialized file position in ms3_readtracelist_selection()

---

extraheaders.c
libmseed.h
pack.c
test/test-extraheaders.c
unpack.c
yyjson.c
yyjson.h

* Update yyjson to the 0.7.0 release
* Use the new JSON Pointer-based API to apply changes in `mseh_set_ptr_r()`
* Rename mseh_* routines and arguments from `path` to `ptr` to avoid confusion
* Add tests for extra header functionality

Update yyjson to 0.7.0, use more efficient API, add tests

---

ChangeLog
genutils.c
libmseed.h
msrutils.c
pack.c
unpack.c

- Print sample rate in Hz consistently in msr3_print()
- Read and write microsecond offsets to/from Blockette 500 (v2)
- Fix addition of Clock Model field 9 of Blockette 500 (v2)
- Fix writing of MEDSNR field of Blockette 201 (miniSEED v2)

Merge changes from develop for v3.0.15

---

ChangeLog
libmseed.h
parseutils.c
unpack.c
unpack.h

- Add `const` qualifier to record pointer declarations where the interface does not modify the data and the `MS3Record.record` pointer, which should not be modified.

Add const qualifier to record pointer declarations

---

ChangeLog
extraheaders.c
fileutils.c
libmseed.h
lookup.c
msrutils.c
selection.c
test/test-selection.c
tracelist.c
unpack.c
unpackdata.c
unpackdata.h

**Changes**:
- Do not declare pass-by-value function params as `const`
- Implement const-correctness throughout the library

Const params
